name: Publish
# When a new Github Release is created, publish to NPM
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Setup Node environment
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: NPM Install
        run: npm install
  deploy_chime_prod_demo:
    needs: publish
    name: Prod - Chime Client - Deploy the Serverless Meeting Demos
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: text
      NAME: ChimeProd
    steps:
      - name: Echo npm version
        run: echo "Pre release name:" ${{ github.event.release.tag_name }}
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
#          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
#          aws-session-token: ${{ secrets.PROD_AWS_SESSION_TOKEN }}
#          aws-region: us-east-1
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
#      - name: Checkout Package
#        uses: actions/checkout@v2
#        with:
#          repository: aws/amazon-chime-sdk-js
#          ref: v${{ github.event.release.tag_name }}
#          fetch-depth: 0
#      - name: Install the Chime SDK
#        run: |
#          current_version=2.24.0
#          npm uninstall amazon-chime-sdk-js
#          npm install amazon-chime-sdk-js@$current_version
      - name: Verify npm version
        run: |
          demo_current_version=$(.github/script/get-demo-browser-current-version)
          echo "Current demo version:" $demo_current_version
      - name: Run Deployment Script
        run: script/postrelease
  deploy_chime_prod_demo_iad:
    needs: publish
    name: Prod - ChimeSDKMeetings Client - Deploy the Serverless Meeting Demos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [ ChimeSDKMeetingsProdIAD, ChimeSDKMeetingsProdPDX ]
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: text
      NAME: ${{ matrix.name }}
    steps:
      - name: Echo npm version
        run: echo "Pre release name:" ${{ github.event.release.tag_name }}
      - name: Checkout Package
        uses: actions/checkout@v2
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
#          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
#          aws-session-token: ${{ secrets.PROD_AWS_SESSION_TOKEN }}
#          aws-region: us-east-1
#      - name: Checkout Package
#        uses: actions/checkout@v2
#        with:
#          repository: aws/amazon-chime-sdk-js
#          ref: v${{ github.event.release.tag_name }}
#          fetch-depth: 0
#      - name: Install the Chime SDK
#        run: |
#          current_version=2.24.0
#          cd demos/browser
#          npm uninstall amazon-chime-sdk-js
#          npm install amazon-chime-sdk-js@$current_version
      - name: Verify npm version
        run: |
          demo_current_version=^2.25.0
          echo "Current demo version:" $demo_current_version
          if [[ *$demo_current_version* != "#${{ steps.npm_version.outputs.npm_version }}" ]];
          then
            echo "npm version is not the same as the current version"
          else
            echo "Deploy script"
            script/postrelease
          fi
#      - name: Run Deployment Script
#        run: script/postrelease
